language: r
r: devel
sudo: true
cache: packages
dist: bionic

warnings_are_errors: true

apt_packages:
  - qpdf
r_packages:
  - devtools
r_github_packages:
  - r-lib/covr
  
before_install:
  - mkdir ~/.R && echo 'CXX11=g++ -std=c++11 -g -O2 -fPIC' > ~/.R/Makevars
after_success:
  - Rscript -e 'covr::codecov()'
  
script:
  - R CMD build . ${R_BUILD_ARGS}
  - R CMD check `ls -1t *.tar.gz | head -n 1` ${R_CHECK_ARGS}$

notifications:
  email: false

env:
   global:
     - R_BUILD_ARGS="--no-build-vignettes --no-manual --compact-vignettes=gs+qpdf" 
     - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"

cran: http://cran.rstudio.com